# -*- coding: utf-8 -*-
"""ReceipePlannerWithGroq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zjCOMnv1FeMxZzOR7iDAWBF-XObSq3M
"""

!pip install -q groq chromadb sentence-transformers datasets

from datasets import load_dataset
import json
from sentence_transformers import SentenceTransformer

dataset = load_dataset("datahiveai/recipes-with-nutrition", split="train")
df = dataset.to_pandas().head(5000)

embed_model = SentenceTransformer("all-MiniLM-L6-v2")
print("Dataset & Embedding model loaded")

import chromadb
from chromadb.config import Settings

chromadb.api.shared_system_client.SharedSystemClient._identifier_to_system.clear()

client = chromadb.Client(
    Settings(persist_directory="/content/chroma_db")
)

collection = client.get_or_create_collection(name="recipes")

for idx, row in df.iterrows():
    try:
        nutrition = json.loads(row["nutrition"])
        text = f"""
Recipe Name: {row['recipe_name']}
Ingredients: {row['ingredients']}
Instructions: {row['instructions']}
Calories: {nutrition.get('calories')}
Protein: {nutrition.get('protein')}
Carbs: {nutrition.get('carbs')}
Fat: {nutrition.get('fat')}
"""
        embedding = embed_model.encode(text).tolist()
        collection.add(
            documents=[text],
            embeddings=[embedding],
            ids=[str(idx)]
        )
    except:
        pass

print("✅ Recipes ingested into ChromaDB")

from groq import Groq

GROQ_API_KEY="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"

client = Groq(api_key=GROQ_API_KEY)

def generate_recipe(user_query):
    # 1️⃣ Embed query
    query_embedding = embed_model.encode(user_query).tolist()

    # 2️⃣ Retrieve from vector DB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    context = "\n\n".join(results["documents"][0])

    # 3️⃣ Prompt
    prompt = f"""
You are an intelligent AI recipe planner.

Use the reference recipes to answer the user query.

Reference recipes:
{context}

User request:
{user_query}

Generate:
- Recipe name
- Ingredients with quantities
- Step-by-step instructions
- Estimated calories
"""

    # 4️⃣ Groq API call (UPDATED MODEL)
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {"role": "system", "content": "You are a helpful AI recipe planner."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7,
        max_tokens=500
    )

    return response.choices[0].message.content

query = """
Ingredients: banana, oats, almond milk, cocoa powder
Diet: vegan
Calorie limit: 250 per serving
Meal type: dessert/snack
Sweetness: moderate
"""

print(generate_recipe(query))